pub const NPROC: usize = 64; // Maximum number of processes
pub const KSTACKSIZE: usize = 4096; // Size of per-process kernel stack
pub const NCPU: usize = 128; // Maximum number of CPUs
pub const NOFILE: usize = 16; // Open files per process
pub const NFILE: usize = 100; // Open files per system
pub const NLINK_DEREF: usize = 31; // Max amount of symlink dereferences
pub const NINODE: usize = 50; // Max number of active i-nodes
pub const NDEV: usize = 10; // Max major device number
pub const ROOTDEV: u32 = 1; // Device number of file system root disk
pub const MAXARG: usize = 32; // Max exec arguments
pub const MAXOPBLOCKS: usize = 10; // Max # of blocks any FS op writes
pub const LOGSIZE: usize = MAXOPBLOCKS * 3; // Max data blocks in on-disk log
pub const NBUF: usize = MAXOPBLOCKS * 3; // Size of disk block cache
pub const FSSIZE: usize = 10 * 1024; // Size of file system in blocks
pub const MAXGROUPS: usize = 32; // Max groups there can be
pub const MAX_USERNAME: usize = 256; // Max username length
pub const MAX_PASSWD: usize = 128; // Max password length
pub const MAXENV: usize = 32; // Max environment variables
