[package]
name = "rust_kernel"
version = "0.1.0"
edition = "2024"

[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"

[dependencies]
bindings = { path = "../bindings", version = "0.1.0" }
spin = "0.9"
