[package]
name = "gui"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]

[dependencies]
userspace_bindings = { path = "../userspace_bindings", version = "0.1.0" }
spin = "0.9.8"

[profile.release]
lto = true
